# This file was generated by GoReleaser. DO NOT EDIT.
cask "reeve" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "3982f8df0003cd2031a0af3d9d0febd625bb6c5a08c013c551e81fbde8780c31"
      url "https://github.com/reeveops/reeve/releases/download/v#{version}/reeve_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f8baba92e52968d549cc32231802b9519a8365d02cf5b700c9e490ab2d2a7e21"
      url "https://github.com/reeveops/reeve/releases/download/v#{version}/reeve_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cd0d702db35b15ce35b641c3348fd7649f341b8de576cae64297d7bde89b9f57"
      url "https://github.com/reeveops/reeve/releases/download/v#{version}/reeve_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2cd44dd9423dd736f72b989093772de577bc2e668a38bbd014f9199d75d5dbc7"
      url "https://github.com/reeveops/reeve/releases/download/v#{version}/reeve_#{version}_linux_arm64.tar.gz"
    end
  end

  name "reeve"
  desc "PR-native, self-hosted GitOps orchestrator for Pulumi, Terraform, and OpenTofu"
  homepage "https://github.com/reeveops/reeve"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "reeve"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/reeve"]
    end
  end

  # No zap stanza required

end
