# This file was generated by GoReleaser. DO NOT EDIT.
cask "reeve" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "6af5f2ce6fc38c716347281b490482b279cb139026fd6611d71b47454dd1ac21"
      url "https://github.com/reeveops/reeve/releases/download/v#{version}/reeve_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fba399bd0c380a70458f02983926ddce0727a99b0814baf101b11e97a2b7a3c3"
      url "https://github.com/reeveops/reeve/releases/download/v#{version}/reeve_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7d759fcc1e5a1d0afbce624228024c51f5461951a076d16d84b7b3463ed212cb"
      url "https://github.com/reeveops/reeve/releases/download/v#{version}/reeve_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4c3da7e9c7686ffa7de3cc7a9acfa87c33a935b2ce4868ffd5d5f2976f5421b0"
      url "https://github.com/reeveops/reeve/releases/download/v#{version}/reeve_#{version}_linux_arm64.tar.gz"
    end
  end

  name "reeve"
  desc "PR-native, self-hosted GitOps orchestrator for Pulumi, Terraform, and OpenTofu"
  homepage "https://github.com/reeveops/reeve"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "reeve"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/reeve"]
    end
  end

  # No zap stanza required

end
