# This file was generated by GoReleaser. DO NOT EDIT.
cask "reeve" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "a6e5bc249cfb102d949f98c5eb6eb446d63d1a698dec51b3499f4dc5263f9778"
      url "https://github.com/reeveops/reeve/releases/download/v#{version}/reeve_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "535c077a7c8556804062d264c682fc55a8175194da6f8b281424f6056ff0ef5b"
      url "https://github.com/reeveops/reeve/releases/download/v#{version}/reeve_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "afcb0b8b64f4a4fc028d04c6cce55ee11e9f47411e0d9ad8f7e1630b8804be80"
      url "https://github.com/reeveops/reeve/releases/download/v#{version}/reeve_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b74772033613e5856020ae087919b7c67b202fb2f34162e606c2fee47e9b6924"
      url "https://github.com/reeveops/reeve/releases/download/v#{version}/reeve_#{version}_linux_amd64.tar.gz"
    end
  end

  name "reeve"
  desc "PR-native, self-hosted GitOps orchestrator for Pulumi, Terraform, and OpenTofu"
  homepage "https://github.com/reeveops/reeve"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "reeve"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/reeve"]
    end
  end

  # No zap stanza required
end
